POST {{service_base_url}}/oauth/token
Accept: application/json
Content-Type: application/json

{
    "grant_type": "password",
    "client_id": "{{oauth_grant_client_id}}",
    "client_secret": "{{oauth_grant_client_secret}}",
    "username": "me@josepostiga.com",
    "password": "123456789"
}

> {%
    if (response.status === 200) {
        client.global.set("oauth_access_token", response.body.access_token);
    }
%}
