version: "3.7"

services:
  organization.server:
    image: nginx
    expose:
      - 80
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.docker/server.conf:/etc/nginx/conf.d/server.conf:ro
      - ./:/var/www/html
    restart: unless-stopped
    networks:
      - app_network

  organization.service:
    image: josepostiga/php:7.4-fpm
    user: "1000:1000"
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    networks:
      - app_network
      - data_network

  organization.db:
    image: mariadb
    environment:
      MYSQL_DATABASE: organization
    expose:
      - 3306
    volumes:
      - itsoup-organization-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - data_network

volumes:
  itsoup-organization-db:

networks:
  app_network:
  data_network:
