PATCH {{service_base_url}}/customers/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{oauth_access_token}}

{
    "name": "YET Another Example Company Ltd (EDITED)",
    "vat_number": "123459876",
    "country": "pt"
}
