GET {{service_base_url}}/users/2
Accept: application/json
Authorization: Bearer {{oauth_access_token}}

###

GET {{service_base_url}}/users/2?include=customer
Accept: application/json
Authorization: Bearer {{oauth_access_token}}
