GET {{service_base_url}}/roles
Accept: application/json
Authorization: Bearer {{oauth_access_token}}

###

GET {{service_base_url}}/roles?deleted=true
Accept: application/json
Authorization: Bearer {{oauth_access_token}}

###

GET {{service_base_url}}/roles?include=customer
Accept: application/json
Authorization: Bearer {{oauth_access_token}}
