PATCH {{service_base_url}}/roles/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{oauth_access_token}}

{
    "name": "EDITED Role",
    "scopes": [
        "organization:customers:view",
        "organization:customers:manage",
        "organization:roles:view",
        "organization:roles:manage",
        "organization:users:view",
        "organization:users:manage"
    ]
}
